### ISSUE TITLE
Mirage fails to start due to imports from testing package

### ISSUE THREAD

**Issue by rusenask** [SpectoLabs/mirage#33]
Mirage fails to start due to missing dependencies. Testing package shouldn't normally be imported during run and those dependencies aren't expected or used by the application. However, recent changes to tracker collection indexing imported a function from admin/scripts.py so it also tried to import other dependencies that this file had. This results in:

>(stubo-prod)Karoliss-MacBook-Pro:mirage karolisrusenas$ python run.py 
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    main()
  File "run.py", line 29, in main
    from stubo.service.run_stubo import TornadoManager
  File "/Users/karolisrusenas/IdeaProjects/mirage/stubo/service/run_stubo.py", line 26, in <module>
    from stubo.scripts.admin import create_tracker_collection
  File "/Users/karolisrusenas/IdeaProjects/mirage/stubo/scripts/admin.py", line 17, in <module>
    from stubo.testing import DummyRequestHandler
  File "/Users/karolisrusenas/IdeaProjects/mirage/stubo/testing.py", line 258, in <module>
    import ming

**Comment by rusenask** [comment]
fixed and merged
